assets:
  settings.xml: minlessika/home#assets/settings.xml
  public.key: minlessika/home#assets/public.key
  private.key: minlessika/home#assets/private.key
architect:
  - baudoliver7
install: |
  javac -version
release:
    script: |-
     gpg --import /home/r/public.key
     gpg --allow-secret-key-import --import --batch --pinentry-mode=loopback /home/r/private.key 
     mvn versions:set "-DnewVersion=${tag}"
     git commit -am "${tag}"
     mvn clean install -Dinvoker.skip
     mvn clean deploy -Psonatype,surati --errors --settings /home/r/settings.xml -Dstyle.color=never
